### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by KirinHao** [dennisvdang/chorus-detection#1]
Dear dennisvdang, thank you for sharing. I am very interested in chorus detection. I would like to ask how can I get the dataset for training, or can you share the model best_model .h5, thank you very much.

**Comment by dennisvdang** [comment]
Hi, thanks for showing interest! I just uploaded best_model.h5. The dataset contains music that I'm not allowed to distribute due to copyright, however, you can use the preprocessing notebook or adapt it to create your own training dataset on your own music.

**Comment by KirinHao** [comment]
Ok, thank you!

**Comment by KirinHao** [comment]
I have another question. In practice, does deep learning use tensorflow more? I am a beginner, and I first came into contact with PyTorch, so I know less about this aspect.

> Hi, thanks for showing interest! I just uploaded best_model.h5. The dataset contains music that I'm not allowed to distribute due to copyright, however, you can use the preprocessing notebook or adapt it to create your own training dataset on your own music.

**Comment by dennisvdang** [comment]
From what I've seen so far, a lot of academic research uses PyTorch and PyTorch's API is more user-friendly/intuitive. I ran into an issue (I forgot what exactly) when trying to build my model using PyTorch and TensorFlow allowed me to do what I wanted so I just went with that. I'd suggest to try doing different projects with both and see which one you like better!
